In [1]:
import numpy as np
import itertools
np.seterr(divide='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
class Bar:
    def __init__(self, title, dia, length, number):
        self.title = title
        self.dia = dia
        self.length = length
        self.number = number

In [3]:
def get_bar_length_array(barList):
    arr =[]
    for x in barList:
        arr.append(x.length)
    return np.array(arr)

In [4]:
def get_bar_number_array(barList):
    arr =[]
    for x in barList:
        arr.append(x.number)
    return np.array(arr)

In [5]:
def get_coefficien_list(L, bar_length_array):
    bar_length_min = min(bar_length_array)
    max_iter = int(L/bar_length_min)+1
    co_efficient_list = np.arange(max_iter)

    product_arguments = [co_efficient_list]*len(bar_length_array)

    # print(product_arguments)
    return list(itertools.product(*product_arguments))

In [6]:
def get_coefficien_arr(L, bar_length_array):
    coefficien_arr = np.array(get_coefficien_list(L, bar_length_array))

    sum_arr = np.sum(coefficien_arr*bar_length_array, axis=1)
    # Remove all item which sum length = 0 or greater than L
    condition = (sum_arr == 0) | (sum_arr > L)
    condition = np.invert(condition)

    return coefficien_arr[condition]

In [7]:
L = 12
# bar_length_list = [2.5, 3, 4]

# bar1 = Bar('A', 12, 1.5, 450)
# bar2 = Bar('B', 12, 2, 430)
# bar3 = Bar('C', 12, 4, 600)
# bar4 = Bar('D', 12, 5.5, 854)
# bar5 = Bar('E', 12, 7.5, 530)
# bar6 = Bar('F', 12, 8.5, 745)

# bar1 = Bar('A', 12, 1.5, 1000)
# bar2 = Bar('B', 12, 2, 2000)
# bar3 = Bar('C', 12, 4, 328)
# bar4 = Bar('D', 12, 5.5, 854)
# bar5 = Bar('E', 12, 7.5, 530)
# bar6 = Bar('F', 12, 8.5, 500)

# bar1 = Bar('A', 12, 1.5, 300)
# bar2 = Bar('B', 12, 2, 700)
# bar3 = Bar('C', 12, 4, 600)
# bar4 = Bar('D', 12, 5.5, 210)
# bar5 = Bar('E', 12, 7.5, 530)
# bar6 = Bar('F', 12, 8.5, 555)

bar1 = Bar('A', 12, 1.5, 1000)
bar2 = Bar('B', 12, 2.5, 2000)
bar3 = Bar('C', 12, 4, 328)
bar4 = Bar('D', 12, 6.5, 450)
bar5 = Bar('E', 12, 7.5, 530)
bar6 = Bar('F', 12, 8.5, 2000)

In [8]:
barList = [bar1,bar2,bar3,bar4,bar5,bar6]
bar_length_array = get_bar_length_array(barList)
bar_number_array = get_bar_number_array(barList)

In [9]:
coefficient_list = get_coefficien_arr(L,bar_length_array)

In [10]:
bar_length_array

array([1.5, 2.5, 4. , 6.5, 7.5, 8.5])

In [11]:
coefficient_list[:3]

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0]])

In [12]:
index_array = np.where(coefficient_list>0,1,0)

In [13]:
index_array =np.argsort((index_array*bar_length_array).max(axis=1)) 

In [14]:
index_array

array([66, 36, 20, 48, 56, 65, 63, 60, 59, 34, 35, 64, 27, 42, 45, 47, 62,
       19, 32, 52, 14, 54, 55,  8, 58, 17, 53, 46, 44, 41, 61, 40, 57, 51,
       33, 30,  3,  6,  7, 26, 12, 24, 13, 16, 18, 31,  2,  5, 11, 15, 50,
       23, 43, 25, 39, 29, 22, 10, 28, 38,  4,  1, 49, 21,  9, 37,  0],
      dtype=int64)

In [15]:
index_array = index_array[::-1]

In [16]:
index_array

array([ 0, 37,  9, 21, 49,  1,  4, 38, 28, 10, 22, 29, 39, 25, 43, 23, 50,
       15, 11,  5,  2, 31, 18, 16, 13, 24, 12, 26,  7,  6,  3, 30, 33, 51,
       57, 40, 61, 41, 44, 46, 53, 17, 58,  8, 55, 54, 14, 52, 32, 19, 62,
       47, 45, 42, 27, 64, 35, 34, 59, 60, 63, 65, 56, 48, 20, 36, 66],
      dtype=int64)

In [17]:
bbb =coefficient_list[index_array]

In [18]:
results = []

for i,x in enumerate(bar_length_array):
    columnIndex = len(bar_length_array)-1-i
    mask =bbb[:,columnIndex]>0
    f=bbb[mask]
    f_comb=f[np.argsort(L-(f*bar_length_array).sum(axis=1))]
    results.extend(f_comb)

In [19]:
results = np.array(results)

In [20]:
results

array([[2, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [3, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 0],
       [2, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [2, 1, 0, 1, 0, 0],
       [0, 2, 0, 1, 0, 0],
       [3, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [2, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 1, 2, 0, 0, 0],
       [2, 2, 1, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 3, 1, 0, 0, 0],
       [5, 0, 1, 0, 0, 0],
       [2, 0, 2, 0, 0, 0],
       [3, 1, 1, 0, 0, 0],
       [0, 1, 2, 0, 0, 0],
       [1, 2, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [4, 0, 1, 0, 0, 0],
       [1, 0, 2, 0, 0, 0],
       [2, 1, 1, 0, 0, 0],
       [0, 2, 1, 0, 0, 0],
 

In [21]:
final_list = []
for comb in results:
    if bar_number_array.sum()==0:
            break
    cond = bar_number_array!=0
    if comb.sum()==(comb*cond).sum():
        min_arr = bar_number_array/comb
        cut = int(np.nanmin(min_arr))
        if cut !=0:
            bar_number_array = bar_number_array - comb*cut
            westage = L-(bar_length_array*comb).sum()
            result = {'cut':cut,'combination':comb,'westage_per_cut':westage,'total_westage':cut*westage,'L':L}
            final_list.append(result)

C:\Users\sohel\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


In [22]:
final_list

[{'cut': 500,
  'combination': array([2, 0, 0, 0, 0, 1]),
  'westage_per_cut': 0.5,
  'total_westage': 250.0,
  'L': 12},
 {'cut': 1500,
  'combination': array([0, 1, 0, 0, 0, 1]),
  'westage_per_cut': 1.0,
  'total_westage': 1500.0,
  'L': 12},
 {'cut': 328,
  'combination': array([0, 0, 1, 0, 1, 0]),
  'westage_per_cut': 0.5,
  'total_westage': 164.0,
  'L': 12},
 {'cut': 202,
  'combination': array([0, 1, 0, 0, 1, 0]),
  'westage_per_cut': 2.0,
  'total_westage': 404.0,
  'L': 12},
 {'cut': 149,
  'combination': array([0, 2, 0, 1, 0, 0]),
  'westage_per_cut': 0.5,
  'total_westage': 74.5,
  'L': 12},
 {'cut': 301,
  'combination': array([0, 0, 0, 1, 0, 0]),
  'westage_per_cut': 5.5,
  'total_westage': 1655.5,
  'L': 12}]

In [23]:
total = 0
for x in final_list:
    total = total+x['cut']

In [24]:
total

2980

In [25]:
mask =bbb[:,len(bar_length_array)-1]>0

In [26]:
first = bbb[mask]

In [27]:
np.argsort(L-(first*bar_length_array).sum(axis=1))

array([1, 2, 3, 0], dtype=int64)

In [28]:
L-(first*bar_length_array).sum(axis=1)

array([3.5, 0.5, 1. , 2. ])

In [29]:
first_comb =first[np.argsort(L-(first*bar_length_array).sum(axis=1))]

In [30]:
first_comb

array([[2, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])

In [31]:
for comb in first_comb:
    if bar_number_array.sum()==0:
            break
    cond = bar_number_array!=0
    if comb.sum()==(comb*cond).sum():
        min_arr = bar_number_array/comb
        cut = int(np.nanmin(min_arr))
        if cut !=0:
            bar_number_array = bar_number_array - comb*cut
            westage = L-(bar_length_array*comb).sum()
            result = {'cut':cut,'combination':comb,'westage_per_cut':westage,'total_westage':cut*westage,'L':L}
            print(result)